# Generated by Django 2.0.4 on 2018-04-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('magnet_uri', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='')),
            ],
        ),
    ]
